### ISSUE TITLE
Request to update the code to the latest version of raisim.🙏🙏🙏

### ISSUE THREAD

**Issue by chillybird** [ZJU-XMech/PhaseGuidedControl#1]

**Comment by cyoahs** [comment]
In progress... and hopefully in two weeks.

**Comment by chillybird** [comment]
Thank you. 🙏

**Comment by chillybird** [comment]
> In progress... and hopefully in two weeks.

Is it finished ? 😶

**Comment by cyoahs** [comment]
> > In progress... and hopefully in two weeks.
> 
> Is it finished ? 😶

Sorry for the reply in vocation. As suggested by peers, the only uncompitable issue resulted for new version of raisim is that the return of  `getImpulse()` method has switched to instance from pointer. 

The current version should work. You can try to compile the code. Feel free to open new issue or reopen this issue as soon as you get in trouble.

**Comment by chillybird** [comment]
> > > In progress... and hopefully in two weeks.
> > 
> > 
> > Is it finished ? no_mouth
> 
> Sorry for the reply in vocation. As suggested by peers, the only uncompitable issue resulted for new version of raisim is that the return of `getImpulse()` method has switched to instance from pointer.
> 
> The current version should work. You can try to compile the code. Feel free to open new issue or reopen this issue as soon as you get in trouble.

I understand, thank you for your reply.
